### PR TITLE
Added MIT License 

### PR DESCRIPTION
**Pull request by mayurdw**
I included our names in the license. We can change it later, it was the easiest license for now.

@TropicalPenguin @emimnemonic @musedivision

### CODE REVIEW

**Comment by TropicalPenguin** [comment]
I think you bring up an important point here: it seems a lot easier to reach agreement on a license when there are few people who have contributed source code; new contributors are effectively buying into whatever license has been established.

I have no objections to the MIT license, but I suspect everyone who has contributed code needs to sign off on this choice; from `git shortlog -sn`, Joseph Payne is also included here.

**Comment by mayurdw** [comment]
@TropicalPenguin I don't know how to make contributors sign off on this and who is Joseph Payne?

**Comment by TropicalPenguin** [comment]
I didn't mean sign off too literally; just that everyone should at least agree informally.

[Joseph Payne](https://www.meetup.com/houseofcode/members/240361087/) made [this commit](https://github.com/codeforprojects/kaideals/commit/fa29215b97730d95279283a06b4a9dc1a11a2ac2).

**Comment by mayurdw** [comment]
I think this can be merged now @TropicalPenguin @musedivision

**Comment by TropicalPenguin** [comment]
Happy with this @Kavithashivani?

**Pull request merged**
